### ISSUE TITLE
Create a simple movies list view

### ISSUE THREAD

**Issue by vnu** [vnu/Flickz#2]
### As a user,
- [x] I should be able to view the list of movies
- [x] I should be able to view the images in the list
- [x] I want to view some details before deciding whether I want to read more
### Implementation constraints
- [x] Image should load asynchronously 
### Tasks
- [x] Setup Pods and add AFNetworking
- [x] Turn Off App Transport Security
- [x] Add Table View
- [x] Add Movie model
- [x] Add a table view cell  (Go with this approach over inline prototype cell to easily try out some designs)
- [x] Add the xib through the view controller
- [x] Add AFNetworking fetch method, pass successCallback
### Sample Json for Now playing movie

``` json
{"page":1,"results":[{"poster_path":"\/k1QUCjNAkfRpWfm1dVJGUmVHzGv.jpg","adult":false,"overview":"Based upon Marvel Comics’ most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.","release_date":"2016-02-09","genre_ids":[35,12,28,878],"id":293660,"original_title":"Deadpool","original_language":"en","title":"Deadpool","backdrop_path":"\/n1y094tVDFATSzkTnFxoGZ1qNsG.jpg","popularity":20.322214,"vote_count":131,"video":false,"vote_average":6.05}],"dates":{"maximum":"2016-02-10","minimum":"2015-12-30"},"total_pages":43,"total_results":857}
```
#### Single Movie

``` json
{
poster_path: "/k1QUCjNAkfRpWfm1dVJGUmVHzGv.jpg",
adult: false,
overview: "Based upon Marvel Comics’ most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
release_date: "2016-02-09",
genre_ids: [
35,
12,
28,
878
],
id: 293660,
original_title: "Deadpool",
original_language: "en",
title: "Deadpool",
backdrop_path: "/n1y094tVDFATSzkTnFxoGZ1qNsG.jpg",
popularity: 20.322214,
vote_count: 131,
video: false,
vote_average: 6.05
}
```

**Comment by vnu** [comment]
Start with static data set before pulling information through API call

**Comment by vnu** [comment]
### Questions
- [ ] Why AFNetworking? Why not alamofire?? https://github.com/Alamofire/Alamofire
- [ ] what is addSubview for?
- [ ] Difference between using indexPathforSelectedRow vs indexPathForCell. Any performance over using one over another.

**Comment by vnu** [comment]
Movies Json List

``` json
{
page: 1,
results: [
{
poster_path: "/k1QUCjNAkfRpWfm1dVJGUmVHzGv.jpg",
adult: false,
overview: "Based upon Marvel Comics’ most unconventional anti-hero, DEADPOOL tells the origin story of former Special Forces operative turned mercenary Wade Wilson, who after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
release_date: "2016-02-09",
genre_ids: [
35,
12,
28,
878
],
id: 293660,
original_title: "Deadpool",
original_language: "en",
title: "Deadpool",
backdrop_path: "/n1y094tVDFATSzkTnFxoGZ1qNsG.jpg",
popularity: 20.322214,
vote_count: 131,
video: false,
vote_average: 6.05
},
{
poster_path: "/cgxEscv6TQRK6a514FwuJOjcqQ5.jpg",
adult: false,
overview: "16-year-old Cassie Sullivan tries to survive in a world devastated by the waves of an alien invasion that has already decimated the population and knocked mankind back to the Stone Age.",
release_date: "2016-01-14",
genre_ids: [
12,
878,
53
],
id: 299687,
original_title: "The 5th Wave",
original_language: "en",
title: "The 5th Wave",
backdrop_path: "/9mNklILambgAb1mUm8912yaSjar.jpg",
popularity: 19.711754,
vote_count: 144,
video: false,
vote_average: 5.32
},
{
poster_path: "/24qz9HuZY8K3Cdo4hRWkmztT7gH.jpg",
adult: false,
overview: "Continuing his "legendary adventures of awesomeness", Po must face two hugely epic, but different threats: one supernatural and the other a little closer to his home.",
release_date: "2016-01-23",
genre_ids: [
28,
12,
16,
35,
10751
],
id: 140300,
original_title: "Kung Fu Panda 3",
original_language: "en",
title: "Kung Fu Panda 3",
backdrop_path: "/eHWmEUP4fa7h1Fe7TXfTL7ncDl8.jpg",
popularity: 15.82254,
vote_count: 121,
video: false,
vote_average: 5.81
}],
dates: {
maximum: "2016-02-10",
minimum: "2015-12-30"
},
total_pages: 43,
total_results: 857
}
```
